/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleLayoutRouteImport } from './routes/$locale/_layout'
import { Route as LocaleAboutRouteImport } from './routes/$locale/about'
import { Route as LocaleCartRouteImport } from './routes/$locale/cart'
import { Route as LocaleContactRouteImport } from './routes/$locale/contact'
import { Route as LocalePrivacyRouteImport } from './routes/$locale/privacy'
import { Route as LocaleReturnsRouteImport } from './routes/$locale/returns'
import { Route as LocaleSearchRouteImport } from './routes/$locale/search'
import { Route as LocaleTermsRouteImport } from './routes/$locale/terms'
import { Route as LocaleWishlistRouteImport } from './routes/$locale/wishlist'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as ApiUploadImageRouteImport } from './routes/api/upload-image'
import { Route as LocaleAccountIndexRouteImport } from './routes/$locale/account/index'
import { Route as LocaleAccountAddressesRouteImport } from './routes/$locale/account/addresses'
import { Route as LocaleAccountLoginRouteImport } from './routes/$locale/account/login'
import { Route as LocaleAccountRegisterRouteImport } from './routes/$locale/account/register'
import { Route as LocaleAccountSettingsRouteImport } from './routes/$locale/account/settings'
import { Route as LocaleCheckoutIndexRouteImport } from './routes/$locale/checkout/index'
import { Route as LocaleCheckoutConfirmationRouteImport } from './routes/$locale/checkout/confirmation'
import { Route as LocaleCollectionsIndexRouteImport } from './routes/$locale/collections/index'
import { Route as LocaleCollectionsCategoryRouteImport } from './routes/$locale/collections/$category'
import { Route as LocaleProductsSlugRouteImport } from './routes/$locale/products/$slug'
import { Route as AdminCategoriesIndexRouteImport } from './routes/admin/categories/index'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin/customers/index'
import { Route as AdminCustomersIdRouteImport } from './routes/admin/customers/$id'
import { Route as AdminDiscountsIndexRouteImport } from './routes/admin/discounts/index'
import { Route as AdminHomepageIndexRouteImport } from './routes/admin/homepage/index'
import { Route as AdminInventoryIndexRouteImport } from './routes/admin/inventory/index'
import { Route as AdminMediaIndexRouteImport } from './routes/admin/media/index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders/index'
import { Route as AdminOrdersIdRouteImport } from './routes/admin/orders/$id'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminProductsIdRouteImport } from './routes/admin/products/$id'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products/new'
import { Route as AdminProfileIndexRouteImport } from './routes/admin/profile/index'
import { Route as AdminReviewsIndexRouteImport } from './routes/admin/reviews/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as LocaleAccountOrdersIndexRouteImport } from './routes/$locale/account/orders/index'
import { Route as LocaleAccountOrdersIdRouteImport } from './routes/$locale/account/orders/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleLayoutRoute = LocaleLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAboutRoute = LocaleAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleCartRoute = LocaleCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleContactRoute = LocaleContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePrivacyRoute = LocalePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleReturnsRoute = LocaleReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSearchRoute = LocaleSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleTermsRoute = LocaleTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleWishlistRoute = LocaleWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => LocaleRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const ApiUploadImageRoute = ApiUploadImageRouteImport.update({
  id: '/api/upload-image',
  path: '/api/upload-image',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleAccountIndexRoute = LocaleAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAccountAddressesRoute = LocaleAccountAddressesRouteImport.update({
  id: '/account/addresses',
  path: '/account/addresses',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAccountLoginRoute = LocaleAccountLoginRouteImport.update({
  id: '/account/login',
  path: '/account/login',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAccountRegisterRoute = LocaleAccountRegisterRouteImport.update({
  id: '/account/register',
  path: '/account/register',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAccountSettingsRoute = LocaleAccountSettingsRouteImport.update({
  id: '/account/settings',
  path: '/account/settings',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleCheckoutIndexRoute = LocaleCheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleCheckoutConfirmationRoute =
  LocaleCheckoutConfirmationRouteImport.update({
    id: '/checkout/confirmation',
    path: '/checkout/confirmation',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleCollectionsIndexRoute = LocaleCollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleCollectionsCategoryRoute =
  LocaleCollectionsCategoryRouteImport.update({
    id: '/collections/$category',
    path: '/collections/$category',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleProductsSlugRoute = LocaleProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => LocaleRoute,
} as any)
const AdminCategoriesIndexRoute = AdminCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersIdRoute = AdminCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscountsIndexRoute = AdminDiscountsIndexRouteImport.update({
  id: '/discounts/',
  path: '/discounts/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomepageIndexRoute = AdminHomepageIndexRouteImport.update({
  id: '/homepage/',
  path: '/homepage/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryIndexRoute = AdminInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaIndexRoute = AdminMediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIdRoute = AdminProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileIndexRoute = AdminProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsIndexRoute = AdminReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRoute,
} as any)
const LocaleAccountOrdersIndexRoute =
  LocaleAccountOrdersIndexRouteImport.update({
    id: '/account/orders/',
    path: '/account/orders/',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleAccountOrdersIdRoute = LocaleAccountOrdersIdRouteImport.update({
  id: '/account/orders/$id',
  path: '/account/orders/$id',
  getParentRoute: () => LocaleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/cart': typeof LocaleCartRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/returns': typeof LocaleReturnsRoute
  '/$locale/search': typeof LocaleSearchRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/$locale/wishlist': typeof LocaleWishlistRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/upload-image': typeof ApiUploadImageRoute
  '/$locale/': typeof LocaleIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$locale/account/addresses': typeof LocaleAccountAddressesRoute
  '/$locale/account/login': typeof LocaleAccountLoginRoute
  '/$locale/account/register': typeof LocaleAccountRegisterRoute
  '/$locale/account/settings': typeof LocaleAccountSettingsRoute
  '/$locale/checkout/confirmation': typeof LocaleCheckoutConfirmationRoute
  '/$locale/collections/$category': typeof LocaleCollectionsCategoryRoute
  '/$locale/products/$slug': typeof LocaleProductsSlugRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/$locale/account/': typeof LocaleAccountIndexRoute
  '/$locale/checkout/': typeof LocaleCheckoutIndexRoute
  '/$locale/collections/': typeof LocaleCollectionsIndexRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/discounts/': typeof AdminDiscountsIndexRoute
  '/admin/homepage/': typeof AdminHomepageIndexRoute
  '/admin/inventory/': typeof AdminInventoryIndexRoute
  '/admin/media/': typeof AdminMediaIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/profile/': typeof AdminProfileIndexRoute
  '/admin/reviews/': typeof AdminReviewsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/$locale/account/orders/$id': typeof LocaleAccountOrdersIdRoute
  '/$locale/account/orders/': typeof LocaleAccountOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/cart': typeof LocaleCartRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/returns': typeof LocaleReturnsRoute
  '/$locale/search': typeof LocaleSearchRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/$locale/wishlist': typeof LocaleWishlistRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/upload-image': typeof ApiUploadImageRoute
  '/admin': typeof AdminIndexRoute
  '/$locale/account/addresses': typeof LocaleAccountAddressesRoute
  '/$locale/account/login': typeof LocaleAccountLoginRoute
  '/$locale/account/register': typeof LocaleAccountRegisterRoute
  '/$locale/account/settings': typeof LocaleAccountSettingsRoute
  '/$locale/checkout/confirmation': typeof LocaleCheckoutConfirmationRoute
  '/$locale/collections/$category': typeof LocaleCollectionsCategoryRoute
  '/$locale/products/$slug': typeof LocaleProductsSlugRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/$locale/account': typeof LocaleAccountIndexRoute
  '/$locale/checkout': typeof LocaleCheckoutIndexRoute
  '/$locale/collections': typeof LocaleCollectionsIndexRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/discounts': typeof AdminDiscountsIndexRoute
  '/admin/homepage': typeof AdminHomepageIndexRoute
  '/admin/inventory': typeof AdminInventoryIndexRoute
  '/admin/media': typeof AdminMediaIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/profile': typeof AdminProfileIndexRoute
  '/admin/reviews': typeof AdminReviewsIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/$locale/account/orders/$id': typeof LocaleAccountOrdersIdRoute
  '/$locale/account/orders': typeof LocaleAccountOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/$locale/_layout': typeof LocaleLayoutRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/cart': typeof LocaleCartRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/returns': typeof LocaleReturnsRoute
  '/$locale/search': typeof LocaleSearchRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/$locale/wishlist': typeof LocaleWishlistRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/upload-image': typeof ApiUploadImageRoute
  '/$locale/': typeof LocaleIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$locale/account/addresses': typeof LocaleAccountAddressesRoute
  '/$locale/account/login': typeof LocaleAccountLoginRoute
  '/$locale/account/register': typeof LocaleAccountRegisterRoute
  '/$locale/account/settings': typeof LocaleAccountSettingsRoute
  '/$locale/checkout/confirmation': typeof LocaleCheckoutConfirmationRoute
  '/$locale/collections/$category': typeof LocaleCollectionsCategoryRoute
  '/$locale/products/$slug': typeof LocaleProductsSlugRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/$locale/account/': typeof LocaleAccountIndexRoute
  '/$locale/checkout/': typeof LocaleCheckoutIndexRoute
  '/$locale/collections/': typeof LocaleCollectionsIndexRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/discounts/': typeof AdminDiscountsIndexRoute
  '/admin/homepage/': typeof AdminHomepageIndexRoute
  '/admin/inventory/': typeof AdminInventoryIndexRoute
  '/admin/media/': typeof AdminMediaIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/profile/': typeof AdminProfileIndexRoute
  '/admin/reviews/': typeof AdminReviewsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/$locale/account/orders/$id': typeof LocaleAccountOrdersIdRoute
  '/$locale/account/orders/': typeof LocaleAccountOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/admin'
    | '/$locale/about'
    | '/$locale/cart'
    | '/$locale/contact'
    | '/$locale/privacy'
    | '/$locale/returns'
    | '/$locale/search'
    | '/$locale/terms'
    | '/$locale/wishlist'
    | '/admin/login'
    | '/api/upload-image'
    | '/$locale/'
    | '/admin/'
    | '/$locale/account/addresses'
    | '/$locale/account/login'
    | '/$locale/account/register'
    | '/$locale/account/settings'
    | '/$locale/checkout/confirmation'
    | '/$locale/collections/$category'
    | '/$locale/products/$slug'
    | '/admin/customers/$id'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/$locale/account/'
    | '/$locale/checkout/'
    | '/$locale/collections/'
    | '/admin/categories/'
    | '/admin/customers/'
    | '/admin/discounts/'
    | '/admin/homepage/'
    | '/admin/inventory/'
    | '/admin/media/'
    | '/admin/orders/'
    | '/admin/products/'
    | '/admin/profile/'
    | '/admin/reviews/'
    | '/admin/settings/'
    | '/$locale/account/orders/$id'
    | '/$locale/account/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale'
    | '/$locale/about'
    | '/$locale/cart'
    | '/$locale/contact'
    | '/$locale/privacy'
    | '/$locale/returns'
    | '/$locale/search'
    | '/$locale/terms'
    | '/$locale/wishlist'
    | '/admin/login'
    | '/api/upload-image'
    | '/admin'
    | '/$locale/account/addresses'
    | '/$locale/account/login'
    | '/$locale/account/register'
    | '/$locale/account/settings'
    | '/$locale/checkout/confirmation'
    | '/$locale/collections/$category'
    | '/$locale/products/$slug'
    | '/admin/customers/$id'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/$locale/account'
    | '/$locale/checkout'
    | '/$locale/collections'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/discounts'
    | '/admin/homepage'
    | '/admin/inventory'
    | '/admin/media'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/profile'
    | '/admin/reviews'
    | '/admin/settings'
    | '/$locale/account/orders/$id'
    | '/$locale/account/orders'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/admin'
    | '/$locale/_layout'
    | '/$locale/about'
    | '/$locale/cart'
    | '/$locale/contact'
    | '/$locale/privacy'
    | '/$locale/returns'
    | '/$locale/search'
    | '/$locale/terms'
    | '/$locale/wishlist'
    | '/admin/login'
    | '/api/upload-image'
    | '/$locale/'
    | '/admin/'
    | '/$locale/account/addresses'
    | '/$locale/account/login'
    | '/$locale/account/register'
    | '/$locale/account/settings'
    | '/$locale/checkout/confirmation'
    | '/$locale/collections/$category'
    | '/$locale/products/$slug'
    | '/admin/customers/$id'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/$locale/account/'
    | '/$locale/checkout/'
    | '/$locale/collections/'
    | '/admin/categories/'
    | '/admin/customers/'
    | '/admin/discounts/'
    | '/admin/homepage/'
    | '/admin/inventory/'
    | '/admin/media/'
    | '/admin/orders/'
    | '/admin/products/'
    | '/admin/profile/'
    | '/admin/reviews/'
    | '/admin/settings/'
    | '/$locale/account/orders/$id'
    | '/$locale/account/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ApiUploadImageRoute: typeof ApiUploadImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_layout': {
      id: '/$locale/_layout'
      path: ''
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleLayoutRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/cart': {
      id: '/$locale/cart'
      path: '/cart'
      fullPath: '/$locale/cart'
      preLoaderRoute: typeof LocaleCartRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/contact': {
      id: '/$locale/contact'
      path: '/contact'
      fullPath: '/$locale/contact'
      preLoaderRoute: typeof LocaleContactRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/privacy': {
      id: '/$locale/privacy'
      path: '/privacy'
      fullPath: '/$locale/privacy'
      preLoaderRoute: typeof LocalePrivacyRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/returns': {
      id: '/$locale/returns'
      path: '/returns'
      fullPath: '/$locale/returns'
      preLoaderRoute: typeof LocaleReturnsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/search': {
      id: '/$locale/search'
      path: '/search'
      fullPath: '/$locale/search'
      preLoaderRoute: typeof LocaleSearchRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/terms': {
      id: '/$locale/terms'
      path: '/terms'
      fullPath: '/$locale/terms'
      preLoaderRoute: typeof LocaleTermsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/wishlist': {
      id: '/$locale/wishlist'
      path: '/wishlist'
      fullPath: '/$locale/wishlist'
      preLoaderRoute: typeof LocaleWishlistRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/upload-image': {
      id: '/api/upload-image'
      path: '/api/upload-image'
      fullPath: '/api/upload-image'
      preLoaderRoute: typeof ApiUploadImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/account/': {
      id: '/$locale/account/'
      path: '/account'
      fullPath: '/$locale/account/'
      preLoaderRoute: typeof LocaleAccountIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/account/addresses': {
      id: '/$locale/account/addresses'
      path: '/account/addresses'
      fullPath: '/$locale/account/addresses'
      preLoaderRoute: typeof LocaleAccountAddressesRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/account/login': {
      id: '/$locale/account/login'
      path: '/account/login'
      fullPath: '/$locale/account/login'
      preLoaderRoute: typeof LocaleAccountLoginRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/account/register': {
      id: '/$locale/account/register'
      path: '/account/register'
      fullPath: '/$locale/account/register'
      preLoaderRoute: typeof LocaleAccountRegisterRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/account/settings': {
      id: '/$locale/account/settings'
      path: '/account/settings'
      fullPath: '/$locale/account/settings'
      preLoaderRoute: typeof LocaleAccountSettingsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/checkout/': {
      id: '/$locale/checkout/'
      path: '/checkout'
      fullPath: '/$locale/checkout/'
      preLoaderRoute: typeof LocaleCheckoutIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/checkout/confirmation': {
      id: '/$locale/checkout/confirmation'
      path: '/checkout/confirmation'
      fullPath: '/$locale/checkout/confirmation'
      preLoaderRoute: typeof LocaleCheckoutConfirmationRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/collections/': {
      id: '/$locale/collections/'
      path: '/collections'
      fullPath: '/$locale/collections/'
      preLoaderRoute: typeof LocaleCollectionsIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/collections/$category': {
      id: '/$locale/collections/$category'
      path: '/collections/$category'
      fullPath: '/$locale/collections/$category'
      preLoaderRoute: typeof LocaleCollectionsCategoryRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/products/$slug': {
      id: '/$locale/products/$slug'
      path: '/products/$slug'
      fullPath: '/$locale/products/$slug'
      preLoaderRoute: typeof LocaleProductsSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/categories'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AdminCategoriesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/$id': {
      id: '/admin/customers/$id'
      path: '/customers/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AdminCustomersIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discounts/': {
      id: '/admin/discounts/'
      path: '/discounts'
      fullPath: '/admin/discounts/'
      preLoaderRoute: typeof AdminDiscountsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homepage/': {
      id: '/admin/homepage/'
      path: '/homepage'
      fullPath: '/admin/homepage/'
      preLoaderRoute: typeof AdminHomepageIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory/': {
      id: '/admin/inventory/'
      path: '/inventory'
      fullPath: '/admin/inventory/'
      preLoaderRoute: typeof AdminInventoryIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media/': {
      id: '/admin/media/'
      path: '/media'
      fullPath: '/admin/media/'
      preLoaderRoute: typeof AdminMediaIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/orders/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/$id': {
      id: '/admin/products/$id'
      path: '/products/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminProductsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile/': {
      id: '/admin/profile/'
      path: '/profile'
      fullPath: '/admin/profile/'
      preLoaderRoute: typeof AdminProfileIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews/': {
      id: '/admin/reviews/'
      path: '/reviews'
      fullPath: '/admin/reviews/'
      preLoaderRoute: typeof AdminReviewsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$locale/account/orders/': {
      id: '/$locale/account/orders/'
      path: '/account/orders'
      fullPath: '/$locale/account/orders/'
      preLoaderRoute: typeof LocaleAccountOrdersIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/account/orders/$id': {
      id: '/$locale/account/orders/$id'
      path: '/account/orders/$id'
      fullPath: '/$locale/account/orders/$id'
      preLoaderRoute: typeof LocaleAccountOrdersIdRouteImport
      parentRoute: typeof LocaleRoute
    }
  }
}

interface LocaleRouteChildren {
  LocaleLayoutRoute: typeof LocaleLayoutRoute
  LocaleAboutRoute: typeof LocaleAboutRoute
  LocaleCartRoute: typeof LocaleCartRoute
  LocaleContactRoute: typeof LocaleContactRoute
  LocalePrivacyRoute: typeof LocalePrivacyRoute
  LocaleReturnsRoute: typeof LocaleReturnsRoute
  LocaleSearchRoute: typeof LocaleSearchRoute
  LocaleTermsRoute: typeof LocaleTermsRoute
  LocaleWishlistRoute: typeof LocaleWishlistRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleAccountAddressesRoute: typeof LocaleAccountAddressesRoute
  LocaleAccountLoginRoute: typeof LocaleAccountLoginRoute
  LocaleAccountRegisterRoute: typeof LocaleAccountRegisterRoute
  LocaleAccountSettingsRoute: typeof LocaleAccountSettingsRoute
  LocaleCheckoutConfirmationRoute: typeof LocaleCheckoutConfirmationRoute
  LocaleCollectionsCategoryRoute: typeof LocaleCollectionsCategoryRoute
  LocaleProductsSlugRoute: typeof LocaleProductsSlugRoute
  LocaleAccountIndexRoute: typeof LocaleAccountIndexRoute
  LocaleCheckoutIndexRoute: typeof LocaleCheckoutIndexRoute
  LocaleCollectionsIndexRoute: typeof LocaleCollectionsIndexRoute
  LocaleAccountOrdersIdRoute: typeof LocaleAccountOrdersIdRoute
  LocaleAccountOrdersIndexRoute: typeof LocaleAccountOrdersIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleLayoutRoute: LocaleLayoutRoute,
  LocaleAboutRoute: LocaleAboutRoute,
  LocaleCartRoute: LocaleCartRoute,
  LocaleContactRoute: LocaleContactRoute,
  LocalePrivacyRoute: LocalePrivacyRoute,
  LocaleReturnsRoute: LocaleReturnsRoute,
  LocaleSearchRoute: LocaleSearchRoute,
  LocaleTermsRoute: LocaleTermsRoute,
  LocaleWishlistRoute: LocaleWishlistRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleAccountAddressesRoute: LocaleAccountAddressesRoute,
  LocaleAccountLoginRoute: LocaleAccountLoginRoute,
  LocaleAccountRegisterRoute: LocaleAccountRegisterRoute,
  LocaleAccountSettingsRoute: LocaleAccountSettingsRoute,
  LocaleCheckoutConfirmationRoute: LocaleCheckoutConfirmationRoute,
  LocaleCollectionsCategoryRoute: LocaleCollectionsCategoryRoute,
  LocaleProductsSlugRoute: LocaleProductsSlugRoute,
  LocaleAccountIndexRoute: LocaleAccountIndexRoute,
  LocaleCheckoutIndexRoute: LocaleCheckoutIndexRoute,
  LocaleCollectionsIndexRoute: LocaleCollectionsIndexRoute,
  LocaleAccountOrdersIdRoute: LocaleAccountOrdersIdRoute,
  LocaleAccountOrdersIndexRoute: LocaleAccountOrdersIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCustomersIdRoute: typeof AdminCustomersIdRoute
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
  AdminProductsIdRoute: typeof AdminProductsIdRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
  AdminDiscountsIndexRoute: typeof AdminDiscountsIndexRoute
  AdminHomepageIndexRoute: typeof AdminHomepageIndexRoute
  AdminInventoryIndexRoute: typeof AdminInventoryIndexRoute
  AdminMediaIndexRoute: typeof AdminMediaIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminProfileIndexRoute: typeof AdminProfileIndexRoute
  AdminReviewsIndexRoute: typeof AdminReviewsIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCustomersIdRoute: AdminCustomersIdRoute,
  AdminOrdersIdRoute: AdminOrdersIdRoute,
  AdminProductsIdRoute: AdminProductsIdRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
  AdminDiscountsIndexRoute: AdminDiscountsIndexRoute,
  AdminHomepageIndexRoute: AdminHomepageIndexRoute,
  AdminInventoryIndexRoute: AdminInventoryIndexRoute,
  AdminMediaIndexRoute: AdminMediaIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminProfileIndexRoute: AdminProfileIndexRoute,
  AdminReviewsIndexRoute: AdminReviewsIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ApiUploadImageRoute: ApiUploadImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
